"""Consideration-factor registry loader + the "apply chosen factors to profile" step.

The simplified flow:  category known -> present ≤4 factors (3-layer language) ->
user picks priority factor(s) A/B/C/D -> those choices boost ranking weights and/or
set the budget tier -> rank -> decision.py picks 1 dominant or 3 near-tie products.

This module is the seam between the UI's factor choices and the ranking engines'
existing weight-boost mechanism. It never touches prices/specs — only maps a chosen
factor id to a `weight_key` (which `_weights()` already knows how to boost) and, for
the budget factor, to a budget_min/budget_max from the price quartiles.

Registry is generated by scripts/gen_factors_registry.py into factors_registry.json.
"""
from __future__ import annotations

import dataclasses
import json
import os
from functools import lru_cache
from typing import Any

_REGISTRY_PATH = os.path.join(os.path.dirname(__file__), "factors_registry.json")


@lru_cache(maxsize=1)
def load_factors() -> dict[str, Any]:
    """Whole registry {"categories": {name: {factors: [...], room_context?: [...]}}}.
    Cached; returns {} (empty) if the file is missing so the app degrades to the
    plain slot-filling flow instead of crashing."""
    try:
        with open(_REGISTRY_PATH, encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, json.JSONDecodeError):
        return {}


def factors_for(category: str | None) -> list[dict[str, Any]]:
    """The ≤4 consideration factors for a category (empty if none/unknown)."""
    if not category:
        return []
    cats = load_factors().get("categories", {})
    entry = cats.get(category)
    return list(entry.get("factors", [])) if entry else []


def room_context_for(category: str | None) -> list[str]:
    if not category:
        return []
    entry = load_factors().get("categories", {}).get(category)
    return list(entry.get("room_context", [])) if entry else []


def has_factors(category: str | None) -> bool:
    return bool(factors_for(category))


def _factor_by_id(category: str, fid: str) -> dict[str, Any] | None:
    for f in factors_for(category):
        if f.get("id") == fid:
            return f
    return None


def choose_factors_payload(category: str) -> dict[str, Any]:
    """The `mode:"choose_factors"` response body: factors tagged A/B/C/D with all
    three language layers + budget tier options, plus a short intro message."""
    letters = "ABCDEFGH"
    out_factors = []
    for i, f in enumerate(factors_for(category)):
        item = {
            "id": f["id"],
            "letter": letters[i] if i < len(letters) else str(i + 1),
            "spec_label": f.get("spec_label", ""),
            "simple_label": f.get("simple_label", ""),
            "contextual": f.get("contextual", []),
            "budget_tier": bool(f.get("budget_tier")),
        }
        if f.get("budget_tier") and f.get("tiers"):
            t = f["tiers"]
            # thấp / trung bình / cao = q25 / q50 / q75 (đ)
            item["tier_options"] = [
                {"key": "low", "label": "Thấp", "hint": f"≤ {t['low']/1_000_000:.0f} triệu"},
                {"key": "mid", "label": "Trung bình", "hint": f"~ {t['mid']/1_000_000:.0f} triệu"},
                {"key": "high", "label": "Cao", "hint": f"~ {t['high']/1_000_000:.0f} triệu"},
            ]
        out_factors.append(item)
    return {
        "category": category,
        "factors": out_factors,
        "room_context": room_context_for(category),
        "message": (f"Để tư vấn {category} sát nhu cầu nhất, anh/chị ưu tiên yếu tố nào "
                    "dưới đây ạ? (chọn tối đa 4)"),
    }


def apply_factor_choices(profile: Any, category: str, chosen: list[str]) -> Any:
    """Return a NeedProfile with the chosen factors applied.

    `chosen` entries are factor ids; the budget factor carries its tier encoded as
    "budget:low" | "budget:mid" | "budget:high". Spec factors append their
    `weight_key` to `factor_priorities` (the ranking engines boost every listed key).
    The budget factor sets budget_min/budget_max from the quartile tier instead.

    Never fabricates: an unknown id is ignored; a budget tier with no numbers falls
    through (user can still type a budget).
    """
    priorities: list[str] = list(getattr(profile, "factor_priorities", []) or [])
    updates: dict[str, Any] = {}

    for raw in chosen or []:
        fid, _, tier = raw.partition(":")
        f = _factor_by_id(category, fid)
        if not f:
            continue
        if f.get("budget_tier"):
            tiers = f.get("tiers") or {}
            if tier in tiers:
                val = int(tiers[tier])
                if tier == "high":
                    # "cao" = trên mốc trung cấp, trần ở mốc cao cấp
                    updates["budget_min"] = int(tiers.get("mid", val))
                    updates["budget_max"] = val
                else:  # low / mid -> trần ở mốc tương ứng
                    updates["budget_max"] = val
            # budget also nudges the price weight so cheaper wins within the tier
            if "price" not in priorities:
                priorities.append("price")
        else:
            wk = f.get("weight_key")
            if wk and wk not in priorities:
                priorities.append(wk)

    updates["factor_priorities"] = priorities
    # dataclasses.replace keeps the profile immutable-ish and carries every other slot
    try:
        return dataclasses.replace(profile, **updates)
    except TypeError:
        # profile isn't a dataclass (defensive) — set attributes in place
        for k, v in updates.items():
            setattr(profile, k, v)
        return profile
